#proxy:
#    build: ./images/proxy
#    container_name: proxy
#    ports:
#        - "1080:1080"
#    environment:
#        TZ: Asia/Shanghai
#    restart: always
#nginx:
#    build: ./images/nginx
#    container_name: nginx 
#    links:
#        - php7
#        - mysql
#        - redis
#    ports:
#        - "80:80"
#        - "443:443"
#    volumes: 
#        - ./works:/data/www
#        - ./volumes/logs/nginx:/var/log/nginx
#        - ./volumes/nginx/sites:/etc/nginx/sites-enabled
#        - ./volumes/nginx/includes:/etc/nginx/includes
#    environment:
#        TZ: Asia/Shanghai
#    restart: always
#php:
#    build: ./images/php7
#    container_name: php
#    ports:
#        - "9000:9000"
#    volumes: 
#        - ./volumes/logs/php7/php:/data/logs/php
#        - ./volumes/logs/php7/php-fpm:/data/logs/php-fpm
#    environment:
#        TZ: Asia/Shanghai
#    restart: always
#php:
#    build: ./images/php5
#    container_name: php
#    ports:
#        - "9000:9000"
#    volumes: 
#        - ./volumes/logs/php5/php:/data/logs/php
#        - ./volumes/logs/php5/php-fpm:/data/logs/php-fpm
#    environment:
#        TZ: Asia/Shanghai
#    restart: always
mysql:
    build: ./images/mysql
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - ./volumes/logs/mysql:/var/log/mysql
        - ./volumes/db/mysql:/var/lib/mysql
    environment:
        TZ: Asia/Shanghai
        MYSQL_ROOT_PASSWORD: "x!21DFe1c4"
    restart: always
#redis:
#    build: ./images/redis
#    container_name: redis 
#    ports:
#        - "6379:6379"
#    volumes: 
#        - ./volumes/db/redis:/data/db/redis
#    environment:
#        TZ: Asia/Shanghai
#    restart: always
# memcached:
#     build: ./images/memcached
#     container_name: memcached 
#     ports:
#         - "11211:11211"
#     environment:
#         TZ: Asia/Shanghai
#     restart: always
#mongodb:
#    build: ./images/mongodb
#    container_name: mongodb
#    ports:
#        - "27018:27017"
#    volumes:
#        - ./volumes/db/mongodb:/data/db
#    environment:
#        TZ: Asia/Shanghai
#    restart: always
