nginx:
    image: daocloud.io/shuc/nginx
    container_name: nginx 
    links:
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes: 
        - ./works:/data/www
        - ./volumes/logs/nginx:/var/log/nginx
        - ./volumes/nginx/sites:/etc/nginx/sites-enabled
        - ./volumes/nginx/includes:/etc/nginx/includes
    restart: always
php:
    image: daocloud.io/shuc/php7
    container_name: php
    ports:
        - "9000:9000"
    volumes: 
        - ./works:/data/www
        - ./volumes/logs/php:/data/logs/php
    restart: always
mysql:
    image: daocloud.io/shuc/mysql
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - ./volumes/db/mysql:/data/db/mysql
        - ./volumes/logs/mysql:/data/logs/mysql
    environment:
        MYSQL_USER: "bileji"
        MYSQL_PASSWORD: "O!g3L70B%F"
        MYSQL_ROOT_PASSWORD: "T41vF!x2L4"
    restart: always
redis:
    image: daocloud.io/shuc/redis
    container_name: redis 
    ports:
        - "6379:6379"
    volumes: 
        - ./volumes/db/redis:/data/db/redis
        - ./volumes/logs/redis:/data/logs/redis
    restart: always
memcached:
    image: daocloud.io/shuc/memcached
    container_name: memcached 
    ports:
        - "11211:11211"
    restart: always
mongodb:
    image: daocloud.io/shuc/mongodb3
    container_name: mongodb
    ports:
        - "27017:27017"
    volumes:
        - ./volumes/db/mongodb:/data/db/mongodb
        - ./volumes/logs/mongodb:/data/logs/mongodb
    environment:
        AUTH: "yes"
        JOURNALING: "yes"
        MONGODB_USER: "root"
        MONGODB_PASS: "541R4evB"
    restart: always
