nginx:
    build: ./images/nginx
    container_name: nginx 
    links:
        - php
    ports:
        - "80:80"
        - "443:443"
        - "8000:8000"
    volumes: 
        - ./works:/data/www
        - ./volumes/logs/nginx:/var/log/nginx
        - ./volumes/nginx/sites:/etc/nginx/sites-enabled
        - ./volumes/nginx/includes:/etc/nginx/includes
    restart: always
php:
    build: ./images/php5
    container_name: php
    ports:
        - "9000:9000"
    volumes: 
        - ./works:/data/www
        - ./volumes/logs/php5/php:/data/logs/php
    restart: always
mysql:
    build: ./images/mysql
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - ./volumes/logs/mysql:/var/log/mysql
        - ./volumes/db/mysql:/var/lib/mysql
    environment:
        MYSQL_USER: "xzt_db"
        MYSQL_PASSWORD: "!dF3BBaf43"
        MYSQL_ROOT_PASSWORD: "x!21DFe1c4"
    restart: always
redis:
    build: ./images/redis
    container_name: redis 
    ports:
        - "6379:6379"
    volumes: 
        - ./volumes/db/redis:/data/db/redis
    restart: always
memcached:
    build: ./images/memcached
    container_name: memcached 
    ports:
        - "11211:11211"
    restart: always
mongodb:
    build: ./images/mongodb
    container_name: mongodb
    ports:
        - "27017:27017"
    volumes:
        - ./volumes/db/mongodb:/data/db
    environment:
        AUTH: "yes"
        JOURNALING: "yes"
        MONGODB_USER: "xzt_db"
        MONGODB_PASS: "841c6e89"
    restart: always
